services:
  frontend:
    build:
      context: ./front
      args:
        NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    env_file:
      - ./front/.env.local
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./back
      args:
        LOG_DIR: ${LOG_DIR}
        IMAGE_UPLOAD: ${IMAGE_UPLOAD}
    ports:
      - "8080:8080"
    env_file:
      - ./back/.env
    environment:
      SPRING_PROFILES_ACTIVE: prod,image-processor
      LOG_DIR: ${LOG_DIR}
      IMAGE_UPLOAD: ${IMAGE_UPLOAD}
      SERVING_UPLOAD: ${SERVING_UPLOAD}
      THUMBNAIL_UPLOAD: ${THUMBNAIL_UPLOAD}
      IMAGE_FILE_SIZE: ${IMAGE_FILE_SIZE}
      MAX_IMAGE_FILES_SIZE: ${MAX_IMAGE_FILES_SIZE}
      ACCESS_TOKEN_EXPIRATION_SECONDS: ${ACCESS_TOKEN_EXPIRATION_SECONDS}
      REFRESH_TOKEN_EXPIRATION_SECONDS: ${REFRESH_TOKEN_EXPIRATION_SECONDS}
      TEMP_PROFILE_IMAGE: ${TEMP_PROFILE_IMAGE}
      THUMBNAIL_WIDTH: ${THUMBNAIL_WIDTH}
      THUMBNAIL_HEIGHT: ${THUMBNAIL_HEIGHT}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - backend-images:${IMAGE_UPLOAD}
      - backend-logs:${LOG_DIR}
    restart: always
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: triptrace
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

volumes:
  mysql-data:
  backend-images:
  backend-logs:
