spring:
  servlet:
    multipart:
      max-file-size: ${IMAGE_FILE_SIZE}
      max-request-size: ${MAX_IMAGE_FILES_SIZE}
custom:
  ext:
    jpg: jpeg
  upload:
    path: ${IMAGE_UPLOAD:/images}
    serving: ${SERVING_UPLOAD:/images/serving}
    thumbnail: ${THUMBNAIL_UPLOAD:/images/thumbnail}
    profile: ${PROFILE_UPLOAD:/images/profile}
  thumbnail:
    width: ${THUMBNAIL_WIDTH:1024}
    height: ${THUMBNAIL_HEIGHT:1024}
