spring:
  datasource:
    url: jdbc:h2:mem:db_test;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
custom:
  ext:
    jpg: jpeg
  upload:
    path: src/test/resources
    serving: /images/serving
    thumbnail: /images/thumbnail
    profile: /images/profile
  thumbnail:
    width: 1024
    height: 1024
