spring:
  servlet:
    multipart:
      max-file-size: ${IMAGE_FILE_SIZE}
      max-request-size: ${MAX_IMAGE_FILES_SIZE}
custom:
  ext:
    jpg: jpeg
  upload:
    path: ${IMAGE_UPLOAD}
    serving: ${SERVING_UPLOAD}
    thumbnail: ${THUMBNAIL_UPLOAD}
    profile: ${PROFILE_UPLOAD}
  thumbnail:
    width: 1024
    height: 1024
